[workspace]
authors = ["Daniele Liprandi <daniele.liprandi@uni-greifswald.com>"]
channels = ["conda-forge"]
name = "VALKStreamlitDashboard"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
streamlit = ">=1.49.1,<2"
requests = ">=2.32.5,<3"
bcrypt = ">=4.3.0,<5"
pandas = ">=2.3.2,<3"
streamlit-aggrid = ">=1.1.8.post1,<2"
matplotlib = ">=3.10.5,<4"
altair = ">=5.5.0,<6"
plotly = ">=6.3.0,<7"
python-dotenv = ">=1.1.1,<2"
